apiVersion: batch/v1
kind: CronJob
metadata:
  name: ai-shorts-maker
spec:
  schedule: "1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: core-system
              image: lacydawun/pro-worker:latest
              imagePullPolicy: Always
              volumeMounts:
                - name: shared-data
                  mountPath: /home/app/AI-Shorts-Maker-Service/Resource/Upload
          imagePullSecrets:
            - name: dockerhub-secret
          volumes:
            - name: shared-data
              hostPath:
                path: /home/fileDisk
                type: Directory
          restartPolicy: OnFailure