apiVersion: v1
clusters:
- cluster:
    token:
    extensions:
    - extension:
        last-update: Sat, 30 Mar 2024 21:29:02 KST
        provider: minikube.sigs.k8s.io
        version: v1.32.0
      name: cluster_info
    server:
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sat, 30 Mar 2024 21:29:02 KST
        provider: minikube.sigs.k8s.io
        version: v1.32.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    token: